import { Product } from "./types";

// Real catalog pulled from akhjewelry.com (2026-09-07): names standardized to
// one system (Title Case) in place of the live site's mix of ALL CAPS and
// Title Case, but every price, material, stone and story detail below is
// the real one from the product's live page. Images are the actual Wix
// media files for that product - see src/lib/wixImage.ts.
//
// FROZEN as of the CMS build (2026-09-09) - this is no longer the live data
// source (see src/lib/products.ts, now Supabase-backed). This file exists
// only as (a) the one-time seed for scripts/seed-products.ts and (b) the
// data source for the frozen /design-concepts historical page, which is
// deliberately decoupled from live DB state. Do not add new products here -
// add them through the CMS at /admin instead.
export const legacyProducts: Product[] = [
  {
    slug: "vahavta-ring",
    name: "V'ahavta Ring",
    category: "Rings",
    price: 900,
    currency: "ILS",
    material: "Sterling silver",
    stone: "Pink tourmaline",
    measurements: "Size 51 (EU) - resizing on request",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    images: [
      "682d76e02811499b9d6b09bab93722ba.jpg",
      "13b41011ba844bf2a6dea1a4c1df04b8.jpg",
      "9aef3c9017634390811dcc80b64536b4.jpg",
      "0af3f7e03542416c88f4473205a22c53.jpg",
    ],
    tagline: "A line worth carrying on the hand.",
    description:
      "A sterling silver band set with a single pink tourmaline, sized 51 and cast in a one-piece run rather than a continuous line.",
    story:
      "Named for a line spoken daily and rarely looked at directly. This ring moves it from the page to the hand.",
    craftsmanship: "Carved in wax, cast in sterling silver, then hand-finished and stone-set at the studio bench.",
    care: "Remove before water or gym work. Polish with a soft cloth; avoid chlorine and perfume contact.",
  },
  {
    slug: "shalva-ring",
    name: "Shalva Be'armonotayich Ring",
    category: "Rings",
    price: 800,
    currency: "ILS",
    material: "Sterling silver",
    stone: "2 white sapphires",
    measurements: "Size 51 (EU) - resizing on request",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    images: [
      "064e5acf9289461bb6cb7002f2e25a50.jpg",
      "852eca58d04346518c2262518ef2651a.jpg",
      "6a8863e9ce5e4ab18485c2ef2f0a135f.jpg",
    ],
    tagline: "Stillness, set in silver.",
    description:
      "A sterling silver band set with two white sapphires, cast in size 51. Resizing is available on request rather than offered as a fixed size run.",
    story: "Named for a blessing of peace within one's own walls - quiet held inside a structure, not outside of it.",
    craftsmanship: "Hand-carved and cast, then set with two matched white sapphires and polished by hand.",
    care: "Store separately to avoid surface scratching. Clean with a jewelry-safe silver cloth.",
  },
  {
    slug: "emerald-ring",
    name: "Emerald Ring",
    category: "Rings",
    price: 9500,
    currency: "ILS",
    material: "9k gold (14k/18k available)",
    stone: "1.66ct emerald",
    measurements: "Made to your ring size",
    availability: "Made to Order",
    dispatch: "Handcrafted to order after your size is confirmed",
    limitedEdition: "One-of-one stone",
    images: [
      "0be6cec73bd24679aa4e00c9cca3fad7.jpeg",
      "cb8ae69ac57c4f80afd55638a03d05de.jpeg",
      "710c6ea3863045298d04afe469f43619.jpeg",
    ],
    tagline: "One stone, cast in gold.",
    description:
      "A 1.66ct emerald set in gold, priced here in 9k with 14k and 18k available on request. Made to order once the piece is confirmed. Note: the second reference photo is an AI-generated visualization of the setting, not the finished piece.",
    story: "Built around one hand-selected emerald rather than a repeatable design - the stone comes first, the setting follows.",
    craftsmanship: "The band is fabricated to the stone's own shape once your gold and size are confirmed.",
    care: "Emeralds are softer than diamonds and can be included internally. Avoid ultrasonic cleaners; wipe with a damp soft cloth only.",
  },
  {
    slug: "white-sapphire-ring",
    name: "White Sapphire Ring",
    category: "Rings",
    price: 700,
    currency: "ILS",
    material: "Sterling silver (gold casting available at a higher price)",
    stone: "2mm white sapphire",
    measurements: "Organic, asymmetric band shape",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    images: ["9e0443bc6f7240bd85d03905a90cee33.jpeg", "ecf790fe2d5a4da4a7c5028e4e4bc06f.png"],
    tagline: "A single stone, set low and worn close.",
    description:
      "A 2mm white sapphire set into an organically shaped silver band. Available for gold casting at a higher price. The second photo is an AI-generated model shown for reference only.",
    story: "The studio's simplest stone ring, built for everyday wear rather than a single occasion.",
    craftsmanship: "Stone-set by hand under magnification, then polished to remove every tool mark from the setting.",
    care: "Sapphires rank 9 on the Mohs scale and are safe for daily wear. Clean with warm water and a soft brush.",
  },
  {
    slug: "kohl-davar-bezmano-ring",
    name: "Kohl Davar Bezmano Ring",
    category: "Rings",
    price: 1200,
    currency: "ILS",
    material: "Sterling silver",
    stone: "2mm emerald, 5mm purple spinel",
    measurements: "Size 60 (EU)",
    availability: "Out of Stock",
    dispatch: "Notify me when restocked",
    images: ["57bb1992a98b4f30ab4c48b62f666eaf.jpeg", "239ef65a707f4eb78b3f4528fb00a2c7.jpeg"],
    tagline: "Everything, in its own time.",
    description:
      "A sterling silver ring set with a 2mm emerald and a 5mm purple spinel, cast in size 60. Currently out of stock while the next casting run is prepared.",
    story:
      "“Kohl davar bezmano” (Hebrew) reminds us that everything comes to our lives in the right timing, even if sometimes it doesn't feel like it.",
    craftsmanship: "Sculpted first in wax by hand before casting and double stone-setting.",
    care: "Polish with a soft cloth. Avoid contact with chlorine, perfume, and household chemicals.",
  },
  {
    slug: "levone",
    name: "Levone Ring",
    category: "Rings",
    price: 700,
    currency: "ILS",
    material: "Sterling silver",
    stone: "Kunzite",
    measurements: "Size 55 (EU) - resizing on request",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    limitedEdition: "SKU 014",
    images: [
      "e9089090481248e2850d43a1bdfe9c15.jpg",
      "7c1f8df6ef9745a2b699005fa4b12dec.jpg",
      "63f151ba86714be1bd3a11a055a9f48c.jpg",
    ],
    tagline: "Best worn after dark.",
    description:
      "A sterling silver ring set with kunzite, a stone that can fade in constant sunlight - which makes this, by design, a ring for evenings.",
    story:
      "Levone was actually not inspired by a flower, but by the moon. Because kunzite's color can fade with sun exposure, it's recommended to wear this one at night - a ring for a moonlight date.",
    craftsmanship: "Hand-carved, cast, then set with kunzite and finished at the bench.",
    care: "Keep out of direct, prolonged sunlight to protect the stone's color. Polish gently with a silver cloth.",
  },
  {
    slug: "anemone",
    name: "Anemone Ring",
    category: "Rings",
    price: 1200,
    currency: "ILS",
    material: "Sterling silver",
    stone: "7 garnets",
    measurements: "Size 56 (EU) - resizing on request",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    limitedEdition: "SKU 012",
    images: [
      "3ecae421f30d48329e7b8fc53d5ce00a.jpg",
      "c6cb68a0af834ed9bd4a0d5eb60a1b08.jpg",
      "c395a25472274f5282e1a57183dbeb20.jpg",
    ],
    tagline: "A field of red, cast in silver.",
    description:
      "Inspired by the anemone flower that fills entire fields with red dots each Israeli winter, a childhood memory for many. Made from sterling silver and set with 7 garnets shaped to look like a field of anemones.",
    story: "A childhood memory of many people in Israel, which makes this ring very sentimental.",
    craftsmanship: "One-piece cast construction set with seven individually placed garnets.",
    care: "Garnets are durable but can chip on hard impact. Remove before manual work.",
  },
  {
    slug: "cala",
    name: "Cala Ring",
    category: "Rings",
    price: 900,
    currency: "ILS",
    material: "Sterling silver",
    stone: "Purple spinel",
    measurements: "Size 54 (EU) - resizing on request",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    limitedEdition: "SKU 013",
    images: [
      "6f9b76fba93c46c7961d50343067d9c2.jpg",
      "18e1e3d0191d4f37b5d5734b2512ac95.jpg",
      "f3fefc19420f4c8a9bbbf41e94a65348.jpg",
    ],
    tagline: "The everyday pinky ring.",
    description:
      "Inspired by the calla lily, with silver wrapping a purple spinel in an organic, imperfect line. A lovely pinky ring built for everyday wear.",
    story: "One of the studio's earliest sculptural forms, kept in the collection unchanged since the first casting run.",
    craftsmanship: "Cast, then hand-finished with a satin brush texture that catches light differently at each angle.",
    care: "Polish with a soft cloth; avoid abrasive cleaners on the brushed surface.",
  },
  {
    slug: "veg",
    name: "Veg Ring",
    category: "Rings",
    price: 300,
    currency: "ILS",
    material: "Sterling silver",
    measurements: "Size 48 (EU)",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    images: ["b65c6e2465eb46549abc4ef917ac781d.jpg", "9059998a3f584fbda668f4854198b469.jpg"],
    tagline: "The studio's simplest silver band.",
    description: "A plain sterling silver ring, cast in size 48. The studio's most affordable, everyday piece.",
    story: "Kept deliberately unadorned - a starting point for stacking with the studio's stone rings.",
    craftsmanship: "Machine-drawn wire, hand-soldered closed and polished, then hand-checked for roundness.",
    care: "Durable for daily wear. Remove before swimming in chlorinated water.",
  },
  {
    slug: "hai-pendant",
    name: "Hai Pendant",
    category: "Necklaces",
    price: 1000,
    currency: "ILS",
    material: "Silver or gold (gold priced higher), 40mm chain",
    stone: "2mm white sapphire",
    measurements: "40mm chain; length and thickness can vary the price",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    images: ["5eb6f38e9e59426aa75a4b9c0dbe0c32.jpeg"],
    tagline: "A small word, worn close to the throat.",
    description:
      "A Hai pendant set with a 2mm white sapphire, cast for silver or gold on a 40mm chain. Price shown is for silver; changing the chain length or thickness changes the price.",
    story: "Named for a two-letter word carried by many, kept small so it reads as personal rather than declarative.",
    craftsmanship: "Pendant and bail are cast as one piece, so the pendant sits flat instead of twisting on the chain.",
    care: "Unclasp before sleeping or swimming. Store flat to prevent chain tangling.",
  },
  {
    slug: "114ct-nigerian-emerald",
    name: "1.14ct Nigerian Emerald Pendant",
    category: "Necklaces",
    price: 11000,
    currency: "ILS",
    material: "9-14k yellow gold, 40mm chain",
    stone: "1.14ct Nigerian emerald, CGRL certified",
    measurements: "40mm chain; 14/18k or other lengths priced accordingly",
    availability: "Made to Order",
    dispatch: "Handcrafted to order",
    limitedEdition: "One-of-one stone",
    images: ["a5d14ff0ef8d4873b925fc364c68c23f.jpeg"],
    tagline: "A certified stone, given its own pendant.",
    description:
      "A 1.14ct Nigerian emerald, CGRL certified, cast for 9-14k yellow gold on a 40mm necklace. Price shown is for 9k gold; 14/18k or a different chain length is priced accordingly.",
    story: "One of the studio's certified stone pieces - the emerald's paperwork travels with the necklace.",
    craftsmanship: "Bezel hand-fabricated to the stone's exact girdle before the chain is attached.",
    care: "Avoid ultrasonic cleaners and heat. Store in the supplied pouch, away from other jewelry.",
  },
  {
    slug: "emerald-pendant",
    name: "3.56ct Pear Shape Nigerian Emerald Necklace",
    category: "Necklaces",
    price: 12500,
    currency: "ILS",
    material: "14k yellow gold (18k available), 40mm chain",
    stone: "3.56ct pear-shape Nigerian emerald, CGRL certified",
    measurements: "40mm chain; 18k or other lengths priced accordingly",
    availability: "Made to Order",
    dispatch: "Handcrafted to order",
    limitedEdition: "One-of-one stone",
    images: [
      "39d61a841cfa435f902a7f9d7ee2f78e.jpeg",
      "973b4fbfeb7b490daccced81bf5ecec1.jpeg",
      "8ec078bbbfb54a8d8e181df0b758acfa.jpeg",
    ],
    tagline: "The studio's largest stone to date.",
    description:
      "A 3.56ct pear-shape Nigerian emerald, CGRL certified, set in 14k yellow gold on a 40mm chain. 18k gold or a different chain length is priced accordingly.",
    story: "This is a one-of-one: once this exact emerald is gone, this exact necklace will not be remade.",
    craftsmanship: "Bezel hand-fabricated to the stone's precise girdle, then chain-soldered link by link.",
    care: "Avoid ultrasonic cleaners and heat. Store in the supplied pouch, away from other jewelry.",
  },
  {
    slug: "maslul",
    name: "Maslul Necklace",
    category: "Necklaces",
    price: 1200,
    currency: "ILS",
    material: "Sterling silver, 45cm chain",
    stone: "Emerald",
    measurements: "Necklace length 45cm",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    limitedEdition: "SKU 011",
    images: [
      "9be53e2123584c17a251fd96ec1af638.jpg",
      "a17f1489c3254f1283c578a078b13ec6.jpeg",
      "39c4ea7e5e434126806084a4edf958e0.jpeg",
    ],
    tagline: "A spiral, worn as a reminder to flow.",
    description:
      "A sterling silver necklace set with an emerald in a spiral pendant, on a 45cm chain. Emerald is a stone associated with emotional balance, echoed in the pendant's spiral shape.",
    story: "A gentle reminder to flow and balance mind, body and soul.",
    craftsmanship: "Hand-carved spiral form, cast in silver, then set with a single emerald.",
    care: "Avoid ultrasonic cleaners on the emerald. Store away from other jewelry to prevent scratching.",
  },
  {
    slug: "bondl",
    name: "Bondl Necklace",
    category: "Necklaces",
    price: 800,
    currency: "ILS",
    material: "Sterling silver, 45cm chain",
    stone: "3 synthetic rubies",
    measurements: "Necklace length 45cm",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    limitedEdition: "SKU 010",
    images: ["e5d94cf386c247f7b0dc9af7129eced7.jpg", "a4183f29ce6d40b8aac3e496ee1db8b8.jpeg"],
    tagline: "Three small rubies, on a fine chain.",
    description: "A sterling silver necklace set with three synthetic rubies, on a 45cm chain.",
    story: "Part of the studio's set-stone necklace line, sized to layer with other pieces.",
    craftsmanship: "Cast in silver, then hand-set with three synthetic rubies and polished.",
    care: "Unclasp before sleeping or swimming. Store flat to prevent chain tangling.",
  },
  {
    slug: "tsil-bangle",
    name: "Tsil Bangle",
    category: "Bracelets",
    price: 1200,
    currency: "ILS",
    material: "Sterling silver",
    stone: "Grey spinel",
    measurements: "One size",
    availability: "In Stock",
    dispatch: "Ships in 2-4 business days",
    images: ["140241ba3a4648c3a32304eada7ec87c.jpeg"],
    tagline: "Solid silver, set with grey spinel.",
    description: "A sterling silver bangle set with grey spinel.",
    story: "The studio's sole bangle design, kept intentionally simple against its stone.",
    craftsmanship: "Cast as a closed form, then hand-polished on a rotating buff to keep the profile true.",
    care: "Polish periodically or let the silver develop a natural patina with wear.",
  },
];

export function getLegacyProductBySlug(slug: string) {
  return legacyProducts.find((p) => p.slug === slug);
}

export function getLegacyRelated(product: Product, max = 4) {
  return legacyProducts
    .filter((p) => p.slug !== product.slug && p.category === product.category)
    .slice(0, max)
    .concat(legacyProducts.filter((p) => p.slug !== product.slug && p.category !== product.category))
    .slice(0, max);
}
