import { Product } from "./types";

// Placeholder catalog. Names are standardized to one system (Title Case, "[Name] [Type]")
// as a replacement for the live site's mixed conventions (e.g. "SHMIRAH VOL 1", "TSIL bangle").
// Prices and a few names are grounded in the real akhjewelry.com catalog; imagery is
// placeholder art until real photography is supplied.
export const products: Product[] = [
  {
    slug: "vahavta-ring",
    name: "V'ahavta Ring",
    category: "Rings",
    price: 900,
    currency: "ILS",
    material: "Recycled sterling silver",
    measurements: "Band width 2.5mm",
    weight: "3.1g",
    availableSizes: ["6", "7", "8", "9"],
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "ring",
    tone: "copper",
    tagline: "A single line, carried on the hand.",
    description:
      "A quiet band with one engraved line running its inner edge, worn where only you can read it. Cast in recycled sterling silver and hand-finished to a soft, brushed surface that ages with wear rather than against it.",
    story:
      "Named for a line spoken daily and rarely looked at. The ring moves that line from the page to the hand, close enough to touch without needing to be seen.",
    craftsmanship:
      "Carved in wax by hand, cast in small batches, then finished and polished at the studio bench. Every ring is inspected individually before it ships.",
    care: "Remove before water or gym work. Polish with a soft cloth; avoid chlorine and perfume contact.",
  },
  {
    slug: "shalva-ring",
    name: "Shalva Be'armonotayich Ring",
    category: "Rings",
    price: 800,
    currency: "ILS",
    material: "Recycled sterling silver",
    measurements: "Band width 3mm, gently domed profile",
    weight: "3.6g",
    availableSizes: ["6", "7", "8", "9", "10"],
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "ring",
    tone: "ink",
    tagline: "Stillness, given a shape you can wear.",
    description:
      "A domed, sculptural band that catches light along its curve rather than through faceting. Comfortable enough for daily wear, substantial enough to notice.",
    story:
      "Built around the idea of quiet held inside a structure, not outside of it. The dome is deliberate: strength without a sharp edge.",
    craftsmanship: "Hand-carved and cast, then domed and polished over several passes to keep the curve even under light.",
    care: "Store separately to avoid surface scratching. Clean with a jewelry-safe silver cloth.",
  },
  {
    slug: "nigerian-emerald-ring",
    name: "Nigerian Emerald Ring",
    category: "Rings",
    price: 9500,
    currency: "ILS",
    material: "18k recycled gold",
    stone: "Nigerian emerald, 1.2ct, hand-selected",
    measurements: "Stone 6.5mm x 5mm, band width 1.8mm",
    weight: "4.2g",
    availableSizes: ["6", "7", "8"],
    availability: "Made to Order",
    dispatch: "Handcrafted to order, ships in 3–4 weeks",
    limitedEdition: "One-of-one setting",
    motif: "ring",
    tone: "stone",
    tagline: "A single stone, chosen before the design.",
    description:
      "Built around one hand-selected Nigerian emerald, set low on a slim 18k gold band so the stone sits close to the finger rather than lifted above it. Each stone is chosen first; the setting is drawn around it.",
    story:
      "Sourced through a small emerald dealer we've worked with directly for three years. No two settings are identical because no two stones are.",
    craftsmanship:
      "The band is hand-fabricated, not cast, so the setting can be built precisely to the stone's own shape and inclusions.",
    care: "Emeralds are softer than diamonds and can be included internally. Avoid ultrasonic cleaners; wipe with a damp soft cloth only.",
  },
  {
    slug: "white-sapphire-ring",
    name: "White Sapphire Ring",
    category: "Rings",
    price: 700,
    currency: "ILS",
    material: "Recycled sterling silver",
    stone: "White sapphire, 4mm, round brilliant",
    measurements: "Stone 4mm, band width 1.6mm",
    weight: "2.4g",
    availableSizes: ["5", "6", "7", "8", "9"],
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "ring",
    tone: "stone",
    tagline: "Clarity, set low and worn close.",
    description:
      "A single round white sapphire set flush into a slim silver band. An everyday stone ring, durable enough for daily wear, quiet enough to layer.",
    story: "The studio's most-repeated design, built for people who want one stone they never have to take off.",
    craftsmanship: "Stone-set by hand under magnification, then polished to remove every tool mark from the setting.",
    care: "Sapphires rank 9 on the Mohs scale and are safe for daily wear. Clean with warm water and a soft brush.",
  },
  {
    slug: "kohl-davar-bezmano-ring",
    name: "Kohl Davar Bezmano Ring",
    category: "Rings",
    price: 850,
    currency: "ILS",
    material: "Recycled sterling silver",
    measurements: "Band width 4mm, sculptural asymmetric face",
    weight: "5.1g",
    availableSizes: ["7", "8", "9"],
    availability: "Out of Stock",
    dispatch: "Notify me when restocked",
    motif: "ring",
    tone: "ink",
    tagline: "Everything, in its own time.",
    description:
      "An asymmetric statement band, wider at the face and tapering toward the back of the hand. Currently out of stock while the next casting run is finished.",
    story: "Named for the idea that everything has its season. This piece returns in small batches rather than staying permanently stocked.",
    craftsmanship: "Sculpted first in wax by hand before casting, which is why the face is never perfectly symmetrical.",
    care: "Polish with a soft cloth. Avoid contact with chlorine, perfume, and household chemicals.",
  },
  {
    slug: "hai-pendant",
    name: "Hai Pendant",
    category: "Necklaces",
    price: 1000,
    currency: "ILS",
    material: "Recycled sterling silver, 45cm chain",
    stone: "White sapphire accent, 2.5mm",
    measurements: "Pendant 14mm, chain 45cm with 5cm extender",
    weight: "2.9g",
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "necklace",
    tone: "copper",
    tagline: "A small word, worn close to the throat.",
    description:
      "A compact pendant set with a single white sapphire, hung on a fine 45cm chain sized to sit just below the collarbone. Layers cleanly under a collar or worn alone.",
    story: "Named for a two-letter word carried by many, kept deliberately small so it reads as personal rather than declarative.",
    craftsmanship: "Pendant and bail are cast as one piece, so the pendant sits flat instead of twisting on the chain.",
    care: "Unclasp before sleeping or swimming. Store flat to prevent chain tangling.",
  },
  {
    slug: "pear-emerald-necklace",
    name: "Pear Emerald Necklace",
    category: "Necklaces",
    price: 12500,
    currency: "ILS",
    material: "18k recycled gold, 42cm chain",
    stone: "3.56ct pear-shape Nigerian emerald",
    measurements: "Stone 12mm x 8mm, chain 42cm",
    weight: "5.8g",
    availability: "Made to Order",
    dispatch: "Handcrafted to order, ships in 3–4 weeks",
    limitedEdition: "One-of-one stone",
    motif: "necklace",
    tone: "stone",
    tagline: "One stone, given a chain of its own.",
    description:
      "A single 3.56ct pear-shape Nigerian emerald, bezel-set on a fine 18k gold chain built to carry its weight without twisting. The studio's largest stone piece to date, made once the stone was in hand.",
    story: "This is a one-of-one: when this exact emerald is gone, this exact necklace will not be remade.",
    craftsmanship: "Bezel hand-fabricated to the stone's precise girdle, then chain-soldered link by link to balance the drop.",
    care: "Avoid ultrasonic cleaners and heat. Store in the supplied pouch, away from other jewelry.",
  },
  {
    slug: "levone-necklace",
    name: "Levone Necklace",
    category: "Necklaces",
    price: 700,
    currency: "ILS",
    material: "Recycled sterling silver, 50cm chain",
    measurements: "Pendant 18mm crescent, chain 50cm",
    weight: "3.4g",
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "necklace",
    tone: "ink",
    tagline: "A sliver, not the whole shape.",
    description:
      "A crescent pendant cast from a hand-carved wax model, deliberately incomplete rather than a full circle. Sits mid-chest on a 50cm chain.",
    story: "Named for the moon in its changing phase, chosen over the full circle to represent things still in progress.",
    craftsmanship: "Hand-carved, cast, then hand-filed along the crescent's inner edge to keep the line soft rather than sharp.",
    care: "Polish gently with a silver cloth; store away from direct sunlight and humidity.",
  },
  {
    slug: "anemone-ring",
    name: "Anemone Ring",
    category: "Rings",
    price: 1200,
    currency: "ILS",
    material: "Recycled sterling silver",
    stone: "Garnet, 3mm cabochon",
    measurements: "Band width 2mm, sculptural petal cluster",
    weight: "4.4g",
    availableSizes: ["6", "7", "8"],
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "ring",
    tone: "copper",
    tagline: "Petals, cast in place.",
    description:
      "A cluster of hand-sculpted petals set with a single cabochon garnet at the center, cast directly from a wax original rather than assembled from parts.",
    story: "Inspired by the anemone flower's fragile, layered structure, translated into a form sturdy enough for daily wear.",
    craftsmanship: "One-piece cast construction. No soldered joints between petals, so the piece holds its shape indefinitely.",
    care: "Garnets are durable but can chip on hard impact. Remove before manual work.",
  },
  {
    slug: "cala-ring",
    name: "Cala Ring",
    category: "Rings",
    price: 900,
    currency: "ILS",
    material: "Recycled sterling silver",
    measurements: "Band width 5mm at widest point, sculptural taper",
    weight: "4.9g",
    availableSizes: ["6", "7", "8", "9"],
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "ring",
    tone: "stone",
    tagline: "One curve, drawn from a single sheet.",
    description:
      "A sculptural band that widens and tapers like a single fold of metal, referencing the calla lily's open curve without depicting it literally.",
    story: "One of the studio's earliest sculptural forms, kept in the collection unchanged since the first casting run.",
    craftsmanship: "Cast, then hand-finished with a satin brush texture that catches light differently at each angle.",
    care: "Polish with a soft cloth; avoid abrasive cleaners on the brushed surface.",
  },
  {
    slug: "maslul-bracelet",
    name: "Maslul Bracelet",
    category: "Bracelets",
    price: 1200,
    currency: "ILS",
    material: "Recycled sterling silver",
    measurements: "Adjustable, fits wrists 15–19cm",
    weight: "8.2g",
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "bangle",
    tone: "ink",
    tagline: "A single path, worn as a loop.",
    description:
      "An open-ended cuff with a hand-hammered surface, adjustable across most wrist sizes. Sits close to the bone without a clasp to catch or fail.",
    story: "Named for the word for path or route, worn as a reminder that the route matters as much as the destination.",
    craftsmanship: "Hand-forged and hammered flat sheet, formed to shape on a mandrel, then finished by hand.",
    care: "Adjust gently with both hands over time. Avoid repeated sharp bending at the same point.",
  },
  {
    slug: "tsil-bangle",
    name: "Tsil Bangle",
    category: "Bracelets",
    price: 1200,
    currency: "ILS",
    material: "Recycled sterling silver",
    measurements: "Fixed diameter, fits wrists up to 17cm",
    weight: "9.6g",
    availableSizes: ["S/M", "M/L"],
    availability: "In Stock",
    dispatch: "Ships in 2–4 business days",
    motif: "bangle",
    tone: "copper",
    tagline: "Solid, closed, and made to outlast a trend.",
    description:
      "A closed, solid bangle with a rounded profile designed for permanent daily wear. The studio's heaviest piece by design, not by accident.",
    story: "Built as a rite-of-passage piece for the studio's longest-standing customers, most of whom never take it off.",
    craftsmanship: "Cast as a closed form, then hand-polished on a rotating buff to keep the round profile true.",
    care: "Solid silver develops a natural patina; polish periodically or let it age as worn.",
  },
  {
    slug: "bondl-ring",
    name: "Bondl Ring",
    category: "Ready to Wear",
    price: 800,
    currency: "ILS",
    material: "Recycled sterling silver",
    measurements: "Band width 3mm, stackable profile",
    weight: "2.8g",
    availableSizes: ["6", "7", "8", "9", "10"],
    availability: "In Stock",
    dispatch: "Ships in 1–2 business days",
    motif: "ring",
    tone: "stone",
    tagline: "The everyday ring, built to be stacked.",
    description:
      "A simple stacking band from the studio's Ready to Wear line: in-stock, sized to order, and built for everyday combination with other pieces.",
    story: "Part of the Ready to Wear collection, made in larger runs so it can ship faster than the studio's one-off pieces.",
    craftsmanship: "Machine-drawn wire, hand-soldered closed and polished, then hand-checked for roundness.",
    care: "Durable for daily wear. Remove before swimming in chlorinated water.",
  },
  {
    slug: "veg-ring",
    name: "Veg Signet Ring",
    category: "Ready to Wear",
    price: 900,
    currency: "ILS",
    material: "Recycled sterling silver",
    measurements: "Signet face 10mm x 8mm",
    weight: "5.5g",
    availableSizes: ["7", "8", "9", "10"],
    availability: "In Stock",
    dispatch: "Ships in 1–2 business days",
    motif: "ring",
    tone: "ink",
    tagline: "A blank signet, left for you to mark.",
    description:
      "A modern signet with a smooth, unengraved face, left deliberately plain. Part of the Ready to Wear line and available for personal engraving on request.",
    story: "Designed as a starting point rather than a finished statement, several customers have since had it engraved with initials or dates.",
    craftsmanship: "Cast in small batches, then hand-polished with the face left flat and unpatterned for engraving.",
    care: "Polish with a soft cloth. If engraved, avoid repeated buffing directly over the engraving.",
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getRelated(product: Product, max = 4) {
  return products
    .filter((p) => p.slug !== product.slug && p.category === product.category)
    .slice(0, max)
    .concat(
      products.filter((p) => p.slug !== product.slug && p.category !== product.category)
    )
    .slice(0, max);
}

export const categories: { name: Product["category"]; blurb: string; tone: Product["tone"] }[] = [
  { name: "Rings", blurb: "Sculptural bands and stone settings, sized to order.", tone: "copper" },
  { name: "Necklaces", blurb: "Pendants and chains, from everyday to one-of-one stones.", tone: "ink" },
  { name: "Bracelets", blurb: "Cuffs and bangles, hand-forged and hammered.", tone: "stone" },
  { name: "Ready to Wear", blurb: "In-stock pieces built for daily wear and faster dispatch.", tone: "copper" },
];
